<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Qxf2                Services_stripe__2e55a3</name>
   <tag></tag>
   <elementGuidId>17d537bf-0892-4755-8060-67e28616b4ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='stripe_checkout_app']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;stripe_checkout_app&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e8bce033-ea1d-4fe6-a949-5d8bfc7c9c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5aae09c8-204e-4935-88b0-e3040ecba98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ef18d86b-2600-4056-918b-99333b52ea24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.stripe.com/v3/oivkx0oP8BgueCG8QFpDfA.html?distinct_id=fa3b944a-1554-e15d-cb18-77d608357d93</value>
      <webElementGuid>98e47065-c8e3-4b28-82d3-86866ad46567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stripe_checkout_app</value>
      <webElementGuid>6ebbc385-ec2a-4d70-b559-690c0031d21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stripe_checkout_app</value>
      <webElementGuid>783a3566-8597-4647-b1fc-8d974dc16408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/iframe[@class=&quot;stripe_checkout_app&quot;]</value>
      <webElementGuid>3e5899de-e81f-4f29-a74b-3bc8d6ead024</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='stripe_checkout_app']</value>
      <webElementGuid>225ce7a8-fe4a-415c-9d87-0deab53a74df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8fa971e7-1a81-439f-ad50-f77cd387d8e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://checkout.stripe.com/v3/oivkx0oP8BgueCG8QFpDfA.html?distinct_id=fa3b944a-1554-e15d-cb18-77d608357d93' and @name = 'stripe_checkout_app']</value>
      <webElementGuid>f7736b52-0b37-47b9-8f98-5ad060742125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
