<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_temperature</name>
   <tag></tag>
   <elementGuidId>c7b9f9c3-ab3a-46d0-921e-4125ea2707b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'temperature']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#temperature</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='temperature']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b08eb63e-b0e1-4bef-a0ea-e0910a615f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>temperature</value>
      <webElementGuid>ac4e3577-4578-45e9-ac80-8371638ad989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>14 ℃</value>
      <webElementGuid>2edcd1a2-51a1-4136-a735-2d0df0173b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;temperature&quot;)</value>
      <webElementGuid>892fbda2-353b-412c-9bf4-184b8c8e4c67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='temperature']</value>
      <webElementGuid>5de4b1b3-5462-4ed0-bda6-8019d4f01ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='weather']/span</value>
      <webElementGuid>b5eecccd-e3e5-44e5-9720-abb9c5d6fbf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current temperature'])[1]/following::span[2]</value>
      <webElementGuid>526037c9-ce72-4a08-bf1a-a58b43838789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moisturizers'])[1]/preceding::span[1]</value>
      <webElementGuid>fc771ad6-b329-467f-aca5-ed34c9a70160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='14']/parent::*</value>
      <webElementGuid>103ba39a-ef97-40da-8dd3-ee9e30f41548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>da599872-e46b-4403-9718-5b945efce531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'temperature' and (text() = '14 ℃' or . = '14 ℃')]</value>
      <webElementGuid>88e1a5f2-215d-4f00-b24a-604f4b04ea93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
